// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=.ts"
// @generated from file examples/v1/examples.proto (package examples.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Examples, IndexRequest } from "./examples_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service examples.v1.ExampleService
 */
export const ExampleService = {
  typeName: "examples.v1.ExampleService",
  methods: {
    /**
     * @generated from rpc examples.v1.ExampleService.Index
     */
    index: {
      name: "Index",
      I: IndexRequest,
      O: Examples,
      kind: MethodKind.Unary,
    },
  }
} as const;

