// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=.ts"
// @generated from file ping/v1/ping.proto (package ping.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FailRequest, FailResponse, PingRequest, PingResponse } from "./ping_pb.ts";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ping.v1.PingService
 */
export const PingService = {
  typeName: "ping.v1.PingService",
  methods: {
    /**
     * @generated from rpc ping.v1.PingService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * @generated from rpc ping.v1.PingService.Fail
     */
    fail: {
      name: "Fail",
      I: FailRequest,
      O: FailResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

